modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/zelythia/AutoTools/issues"
license = "MIT"

[[mods]]
modId="autotools"
version="${version}"
displayName="AutoTools"
displayURL="https://www.curseforge.com/minecraft/mc-mods/autotools"
logoFile="icon.png"
authors="zelythia"
description='''
Automatically switch to the correct tool to use on a block/mob.
'''

[[dependencies.autotools]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.autotools]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20, 1.20.1]"
ordering = "NONE"
side = "CLIENT"
