org.gradle.jvmargs=-Xmx2048M
org.gradle.parallel=true

minecraft_version=1.16.5
enabled_platforms=fabric,forge

maven_group = net.zelythia
archives_name = autotools
mod_version=3.4.2

fabric_loader_version=0.18.4
fabric_api_version=0.42.0+1.16
modmenu_version=1.16.22
cloth_config_version=4.17.101

forge_version=1.16.5-36.2.42
