org.gradle.jvmargs=-Xmx2048M

minecraft_version=26.2
enabled_platforms=fabric,neoforge

maven_group=net.zelythia
archives_name=autotools
mod_version=3.4.3

cloth_config_version=26.2.155
controllable_version=0.26.1+26.2


# Fabric
fabric_loader_version=0.19.5
fabric_api_version=0.159.0+26.2
modmenu_version=20.0.1

# Forge
forge_version=26.2-65.1.3

# Neoforge
neoforge_version=26.2.0.76

