architectury {
    common rootProject.enabled_platforms.split(',')
}

repositories {
    maven { url "https://maven.shedaniel.me/" }
}

loom {
    accessWidenerPath = file("src/main/resources/autotools-common.accesswidener")
}

dependencies {
    // We depend on fabric loader here to use the fabric @Environment annotations and get the mixin dependencies
    // Do NOT use other classes from fabric loader
    implementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"

    api("me.shedaniel.cloth:cloth-config:${rootProject.cloth_config_version}")
}