modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/zelythia/AutoTools/issues"
license = "MIT"

[[mods]]
modId="autotools"
version="${version}"
displayName="AutoTools"
displayURL="https://www.curseforge.com/minecraft/mc-mods/autotools"
logoFile="icon.png"
authors="zelythia"
description='''
Automatically switch to the correct tool to use on a block/mob.
'''

[[dependencies.autotools]]
modId = "neoforge"
type="required"
versionRange = "[20.4,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.autotools]]
modId = "minecraft"
type="required"
versionRange = "[1.20.4]"
ordering = "NONE"
side = "CLIENT"
