name: Publish on GitHub, CurseForge & Modrinth

on: [ workflow_dispatch ]

env:
  MINECRAFT_VERSION: 1.21.9
  VERSION: 3.4.3
  FORGE: false
  NEOFORGE: true
  FABRIC: true
  GITHUB: true
  MAVEN: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      ORG_GRADLE_PROJECT_gprKey: ${{ secrets.GPR_KEY }}

    steps:
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 21

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build Forge
        if: env.FORGE == 'true'
        run: ./gradlew forge:build

      - name: Build Neoforge
        if: env.NEOFORGE == 'true'
        run: ./gradlew neoforge:build

      - name: Build Fabric
        if: env.FABRIC == 'true'
        run: ./gradlew fabric:build

      - name: Publish Forge-Mod on (Curseforge/Modrinth)
        if: env.FORGE == 'true'
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: zgVJyCgK
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 522205
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          files: |
            forge/build/libs/!(*-@(dev|shadow|sources|javadoc)).jar

          name: AutoTools Forge ${{env.MINECRAFT_VERSION}} v${{env.VERSION}}
          version: "${{env.VERSION}}"
          version-type: release
          changelog-file: CHANGELOG.md
          loaders: |
            forge

      - name: Publish Neoforge-Mod on (Curseforge/Modrinth)
        if: env.NEOFORGE == 'true'
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: zgVJyCgK
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 522205
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          files: |
            neoforge/build/libs/!(*-@(dev|shadow|sources|javadoc)).jar

          name: AutoTools NeoForge ${{env.MINECRAFT_VERSION}} v${{env.VERSION}}
          version: "${{env.VERSION}}"
          version-type: release
          changelog-file: CHANGELOG.md
          loaders: |
            neoforge

          dependencies: |
            cloth-config{modrinth:9s6osm5g}{curseforge:348521}#(ignore:github)

      - name: Publish Fabric-Mod on (Curseforge/Modrinth)
        if: env.FABRIC == 'true'
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: zgVJyCgK
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 522205
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          files: |
            fabric/build/libs/!(*-@(dev|shadow|sources|javadoc)).jar

          name: AutoTools Fabric ${{env.MINECRAFT_VERSION}} v${{env.VERSION}}
          version: "${{env.VERSION}}"
          version-type: release
          changelog-file: CHANGELOG.md
          loaders: |
            fabric
            quilt

          dependencies: |
            cloth-config{modrinth:9s6osm5g}{curseforge:348521}#(ignore:github)
            fabric(embedded){modrinth:P7dR8mSH}{curseforge:306612}#(ignore:github)

      - name: Publish Mod on Github
        if: env.GITHUB == 'true'
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          github-token: ${{ secrets.GITH_TOKEN }}

          files: |
            fabric/build/libs/!(*-@(dev|shadow|sources|javadoc)).jar
            fabric/build/libs/*-@(dev|shadow|sources|javadoc).jar
            
            forge/build/libs/!(*-@(dev|shadow|sources|javadoc)).jar
            forge/build/libs/*-@(dev|shadow|sources|javadoc).jar
            
            neoforge/build/libs/!(*-@(dev|shadow|sources|javadoc)).jar
            neoforge/build/libs/*-@(dev|shadow|sources|javadoc).jar

          name: AutoTools Fabric ${{env.MINECRAFT_VERSION}} v${{env.VERSION}}
          version: "${{env.VERSION}}"
          changelog-file: CHANGELOG.md

          github-tag: ${{env.MINECRAFT_VERSION}}-${{env.VERSION}}

      - name: Publish Maven
        if: env.MAVEN == 'true'
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAVEN_USERNAME: ${{secrets.MAVEN_USERNAME}}
          MAVEN_PASSWORD: ${{secrets.MAVEN_PASSWORD}}