name: Publish on GitHub, CurseForge & Modrinth

on: [ workflow_dispatch ]

env:
  MINECRAFT_VERSION: 1.20.4
  VERSION: 2.0
  FABRIC_API_VERSION: 0.96.4+1.20.4

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 17

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build

      - name: Publish Fabric-Mod on (Curseforge/Modrinth)
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: zgVJyCgK
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 522205
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          files: |
            fabric/build/libs/!(*-@(dev|shadow|sources|javadoc)).jar

          name: AutoTools Fabric ${{env.MINECRAFT_VERSION}} v${{env.VERSION}}
          version: "${{env.VERSION}}"
          version-type: release
          changelog-file: CHANGELOG.md
          loaders: |
            fabric
            quilt

          dependencies: |
            fabric@${{env.FABRIC_API_VERSION}}(embedded){modrinth:P7dR8mSH}{curseforge:306612}#(ignore:github)

      - name: Publish Forge-Mod on (Curseforge/Modrinth)
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: zgVJyCgK
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 522205
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          files: |
            forge/build/libs/!(*-@(dev|shadow|sources|javadoc)).jar

          name: AutoTools Forge ${{env.MINECRAFT_VERSION}} v${{env.VERSION}}
          version: "${{env.VERSION}}"
          version-type: release
          changelog-file: CHANGELOG.md
          loaders: |
            forge

      - name: Publish Neoforge-Mod on (Curseforge/Modrinth)
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: zgVJyCgK
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 522205
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          files: |
            neoforge/build/libs/!(*-@(dev|shadow|sources|javadoc)).jar

          name: AutoTools NeoForge ${{env.MINECRAFT_VERSION}} v${{env.VERSION}}
          version: "${{env.VERSION}}"
          version-type: release
          changelog-file: CHANGELOG.md
          loaders: |
            neoforge


      - name: Publish Mod on Github
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          github-token: ${{ secrets.GITH_TOKEN }}

          files: |
            fabric/build/libs/!(*-@(dev|shadow|sources|javadoc)).jar
            fabric/build/libs/*-@(dev|shadow|sources|javadoc).jar
            
            forge/build/libs/!(*-@(dev|shadow|sources|javadoc)).jar
            forge/build/libs/*-@(dev|shadow|sources|javadoc).jar
            
            neoforge/build/libs/!(*-@(dev|shadow|sources|javadoc)).jar
            neoforge/build/libs/*-@(dev|shadow|sources|javadoc).jar

          name: AutoTools Fabric ${{env.MINECRAFT_VERSION}} v${{env.VERSION}}
          version: "${{env.VERSION}}"
          changelog-file: CHANGELOG.md

          github-tag: ${{env.MINECRAFT_VERSION}}-${{env.VERSION}}